CREATE DATABASE users;

\c users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  family VARCHAR(255),
  age INTEGER,
  sex VARCHAR(255),
  created_at TIMESTAMP
);

INSERT INTO users (name, family, age, sex, created_at)
VALUES
  ('John1', 'Doe', 25, 'MALE', NOW()),
  ('John2', 'Doe', 25, 'MALE', NOW()),
  ('John3', 'Doe', 25, 'MALE', NOW()),
  ('John4', 'Doe', 25, 'MALE', NOW()),
  ('John5', 'Doe', 25, 'MALE', NOW()),
  ('John6', 'Doe', 25, 'MALE', NOW()),
  ('John7', 'Doe', 25, 'MALE', NOW()),
  ('John8', 'Doe', 25, 'MALE', NOW()),
  ('John9', 'Doe', 25, 'MALE', NOW()),
  ('John10', 'Doe', 25, 'MALE', NOW()),
  ('John11', 'Doe', 25, 'MALE', NOW()),
  ('John12', 'Doe', 25, 'MALE', NOW()),
  ('John13', 'Doe', 25, 'MALE', NOW()),
  ('John14', 'Doe', 25, 'MALE', NOW()),
  ('John15', 'Doe', 25, 'MALE', NOW()),
  ('John16', 'Doe', 25, 'MALE', NOW()),
  ('John17', 'Doe', 25, 'MALE', NOW()),
  ('John18', 'Doe', 25, 'MALE', NOW()),
  ('John19', 'Doe', 25, 'MALE', NOW()),
  ('John20', 'Doe', 25, 'MALE', NOW()),
  ('John21', 'Doe', 25, 'MALE', NOW()),
  ('John22', 'Doe', 25, 'MALE', NOW()),
  ('John23', 'Doe', 25, 'MALE', NOW()),
  ('John24', 'Doe', 25, 'MALE', NOW()),
  ('John25', 'Doe', 25, 'MALE', NOW()),
  ('John26', 'Doe', 25, 'MALE', NOW()),
  ('John27', 'Doe', 25, 'MALE', NOW()),
  ('John28', 'Doe', 25, 'MALE', NOW()),
  ('John29', 'Doe', 25, 'MALE', NOW()),
  ('John30', 'Doe', 25, 'MALE', NOW()),
  ('John31', 'Doe', 25, 'MALE', NOW()),
  ('John32', 'Doe', 25, 'MALE', NOW()),
  ('John33', 'Doe', 25, 'MALE', NOW()),
  ('John34', 'Doe', 25, 'MALE', NOW()),
  ('John35', 'Doe', 25, 'MALE', NOW()),
  ('John36', 'Doe', 25, 'MALE', NOW()),
  ('John37', 'Doe', 25, 'MALE', NOW()),
  ('John38', 'Doe', 25, 'MALE', NOW()),
  ('John39', 'Doe', 25, 'MALE', NOW()),
  ('John40', 'Doe', 25, 'MALE', NOW()),
  ('John41', 'Doe', 25, 'MALE', NOW()),
  ('John42', 'Doe', 25, 'MALE', NOW()),
  ('John43', 'Doe', 25, 'MALE', NOW()),
  ('John44', 'Doe', 25, 'MALE', NOW()),
  ('John45', 'Doe', 25, 'MALE', NOW()),
  ('John46', 'Doe', 25, 'MALE', NOW()),
  ('John47', 'Doe', 25, 'MALE', NOW()),
  ('John48', 'Doe', 25, 'MALE', NOW()),
  ('John49', 'Doe', 25, 'MALE', NOW()),
  ('John50', 'Doe', 25, 'MALE', NOW()),
  ('John51', 'Doe', 25, 'MALE', NOW()),
  ('John52', 'Doe', 25, 'MALE', NOW()),
  ('John53', 'Doe', 25, 'MALE', NOW()),
  ('John54', 'Doe', 25, 'MALE', NOW()),
  ('John55', 'Doe', 25, 'MALE', NOW()),
  ('John56', 'Doe', 25, 'MALE', NOW()),
  ('John57', 'Doe', 25, 'MALE', NOW()),
  ('John58', 'Doe', 25, 'MALE', NOW()),
  ('John59', 'Doe', 25, 'MALE', NOW()),
  ('John60', 'Doe', 25, 'MALE', NOW()),
  ('John61', 'Doe', 25, 'MALE', NOW()),
  ('John62', 'Doe', 25, 'MALE', NOW()),
  ('John63', 'Doe', 25, 'MALE', NOW()),
  ('John64', 'Doe', 25, 'MALE', NOW()),
  ('John65', 'Doe', 25, 'MALE', NOW()),
  ('John66', 'Doe', 25, 'MALE', NOW()),
  ('John67', 'Doe', 25, 'MALE', NOW()),
  ('John68', 'Doe', 25, 'MALE', NOW()),
  ('John69', 'Doe', 25, 'MALE', NOW()),
  ('John70', 'Doe', 25, 'MALE', NOW()),
  ('John71', 'Doe', 25, 'MALE', NOW()),
  ('John72', 'Doe', 25, 'MALE', NOW()),
  ('John73', 'Doe', 25, 'MALE', NOW()),
  ('John74', 'Doe', 25, 'MALE', NOW()),
  ('John75', 'Doe', 25, 'MALE', NOW()),
  ('John76', 'Doe', 25, 'MALE', NOW()),
  ('John77', 'Doe', 25, 'MALE', NOW()),
  ('John78', 'Doe', 25, 'MALE', NOW()),
  ('John79', 'Doe', 25, 'MALE', NOW()),
  ('John80', 'Doe', 25, 'MALE', NOW()),
  ('John81', 'Doe', 25, 'MALE', NOW()),
  ('John82', 'Doe', 25, 'MALE', NOW()),
  ('John83', 'Doe', 25, 'MALE', NOW()),
  ('John84', 'Doe', 25, 'MALE', NOW()),
  ('John85', 'Doe', 25, 'MALE', NOW()),
  ('John86', 'Doe', 25, 'MALE', NOW()),
  ('John87', 'Doe', 25, 'MALE', NOW()),
  ('John88', 'Doe', 25, 'MALE', NOW()),
  ('John89', 'Doe', 25, 'MALE', NOW()),
  ('John90', 'Doe', 25, 'MALE', NOW()),
  ('John91', 'Doe', 25, 'MALE', NOW()),
  ('John92', 'Doe', 25, 'MALE', NOW()),
  ('John93', 'Doe', 25, 'MALE', NOW()),
  ('John94', 'Doe', 25, 'MALE', NOW()),
  ('John95', 'Doe', 25, 'MALE', NOW()),
  ('John96', 'Doe', 25, 'MALE', NOW()),
  ('John97', 'Doe', 25, 'MALE', NOW()),
  ('John98', 'Doe', 25, 'MALE', NOW()),
  ('John99', 'Doe', 25, 'MALE', NOW()),
  ('John100', 'Doe', 25, 'MALE', NOW()),
  ('John101', 'Doe', 25, 'MALE', NOW()),
  ('John102', 'Doe', 25, 'MALE', NOW()),
  ('John103', 'Doe', 25, 'MALE', NOW()),
  ('John104', 'Doe', 25, 'MALE', NOW()),
  ('John105', 'Doe', 25, 'MALE', NOW()),
  ('John106', 'Doe', 25, 'MALE', NOW()),
  ('John107', 'Doe', 25, 'MALE', NOW()),
  ('John108', 'Doe', 25, 'MALE', NOW()),
  ('John109', 'Doe', 25, 'MALE', NOW()),
  ('John110', 'Doe', 25, 'MALE', NOW()),
  ('John111', 'Doe', 25, 'MALE', NOW()),
  ('John112', 'Doe', 25, 'MALE', NOW()),
  ('John113', 'Doe', 25, 'MALE', NOW()),
  ('John114', 'Doe', 25, 'MALE', NOW()),
  ('John115', 'Doe', 25, 'MALE', NOW()),
  ('John116', 'Doe', 25, 'MALE', NOW()),
  ('John117', 'Doe', 25, 'MALE', NOW()),
  ('John118', 'Doe', 25, 'MALE', NOW()),
  ('John119', 'Doe', 25, 'MALE', NOW()),
  ('Jane', 'Smith', 30, 'FEMALE', NOW());
