# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connect.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='connect.proto',
  package='meow',
  syntax='proto3',
  serialized_options=b'Z1example.com/go-connection-grpc;go_connection_grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rconnect.proto\x12\x04meow\"(\n\x03Msg\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\x05\"Y\n\x08replyMsg\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\x12\t\n\x01p\x18\x04 \x01(\x05\x12\t\n\x01g\x18\x05 \x01(\x05\"R\n\x06NewMsg\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\x12\x0f\n\x07\x61Number\x18\x04 \x01(\x05\"W\n\x0bNewReplyMsg\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\x12\x0f\n\x07\x62Number\x18\x04 \x01(\x05\"\x16\n\x03key\x12\x0f\n\x07\x61uthKey\x18\x01 \x01(\x05\"\x15\n\x03val\x12\x0e\n\x06isTrue\x18\x01 \x01(\x05\x32\x8c\x01\n\x0b\x61uthService\x12%\n\x06req_pq\x12\t.meow.Msg\x1a\x0e.meow.replyMsg\"\x00\x12\x31\n\x0creq_DH_param\x12\x0c.meow.NewMsg\x1a\x11.meow.NewReplyMsg\"\x00\x12#\n\tcheck_key\x12\t.meow.key\x1a\t.meow.val\"\x00\x42\x33Z1example.com/go-connection-grpc;go_connection_grpcb\x06proto3'
)




_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='meow.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='meow.Msg.nonce', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='meow.Msg.message_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=63,
)


_REPLYMSG = _descriptor.Descriptor(
  name='replyMsg',
  full_name='meow.replyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='meow.replyMsg.nonce', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_nonce', full_name='meow.replyMsg.server_nonce', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='meow.replyMsg.message_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p', full_name='meow.replyMsg.p', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='g', full_name='meow.replyMsg.g', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=154,
)


_NEWMSG = _descriptor.Descriptor(
  name='NewMsg',
  full_name='meow.NewMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='meow.NewMsg.nonce', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_nonce', full_name='meow.NewMsg.server_nonce', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='meow.NewMsg.message_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aNumber', full_name='meow.NewMsg.aNumber', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=238,
)


_NEWREPLYMSG = _descriptor.Descriptor(
  name='NewReplyMsg',
  full_name='meow.NewReplyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='meow.NewReplyMsg.nonce', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_nonce', full_name='meow.NewReplyMsg.server_nonce', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='meow.NewReplyMsg.message_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bNumber', full_name='meow.NewReplyMsg.bNumber', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=327,
)


_KEY = _descriptor.Descriptor(
  name='key',
  full_name='meow.key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='authKey', full_name='meow.key.authKey', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=351,
)


_VAL = _descriptor.Descriptor(
  name='val',
  full_name='meow.val',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isTrue', full_name='meow.val.isTrue', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=374,
)

DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.message_types_by_name['replyMsg'] = _REPLYMSG
DESCRIPTOR.message_types_by_name['NewMsg'] = _NEWMSG
DESCRIPTOR.message_types_by_name['NewReplyMsg'] = _NEWREPLYMSG
DESCRIPTOR.message_types_by_name['key'] = _KEY
DESCRIPTOR.message_types_by_name['val'] = _VAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), {
  'DESCRIPTOR' : _MSG,
  '__module__' : 'connect_pb2'
  # @@protoc_insertion_point(class_scope:meow.Msg)
  })
_sym_db.RegisterMessage(Msg)

replyMsg = _reflection.GeneratedProtocolMessageType('replyMsg', (_message.Message,), {
  'DESCRIPTOR' : _REPLYMSG,
  '__module__' : 'connect_pb2'
  # @@protoc_insertion_point(class_scope:meow.replyMsg)
  })
_sym_db.RegisterMessage(replyMsg)

NewMsg = _reflection.GeneratedProtocolMessageType('NewMsg', (_message.Message,), {
  'DESCRIPTOR' : _NEWMSG,
  '__module__' : 'connect_pb2'
  # @@protoc_insertion_point(class_scope:meow.NewMsg)
  })
_sym_db.RegisterMessage(NewMsg)

NewReplyMsg = _reflection.GeneratedProtocolMessageType('NewReplyMsg', (_message.Message,), {
  'DESCRIPTOR' : _NEWREPLYMSG,
  '__module__' : 'connect_pb2'
  # @@protoc_insertion_point(class_scope:meow.NewReplyMsg)
  })
_sym_db.RegisterMessage(NewReplyMsg)

key = _reflection.GeneratedProtocolMessageType('key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'connect_pb2'
  # @@protoc_insertion_point(class_scope:meow.key)
  })
_sym_db.RegisterMessage(key)

val = _reflection.GeneratedProtocolMessageType('val', (_message.Message,), {
  'DESCRIPTOR' : _VAL,
  '__module__' : 'connect_pb2'
  # @@protoc_insertion_point(class_scope:meow.val)
  })
_sym_db.RegisterMessage(val)


DESCRIPTOR._options = None

_AUTHSERVICE = _descriptor.ServiceDescriptor(
  name='authService',
  full_name='meow.authService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=377,
  serialized_end=517,
  methods=[
  _descriptor.MethodDescriptor(
    name='req_pq',
    full_name='meow.authService.req_pq',
    index=0,
    containing_service=None,
    input_type=_MSG,
    output_type=_REPLYMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='req_DH_param',
    full_name='meow.authService.req_DH_param',
    index=1,
    containing_service=None,
    input_type=_NEWMSG,
    output_type=_NEWREPLYMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='check_key',
    full_name='meow.authService.check_key',
    index=2,
    containing_service=None,
    input_type=_KEY,
    output_type=_VAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHSERVICE)

DESCRIPTOR.services_by_name['authService'] = _AUTHSERVICE

# @@protoc_insertion_point(module_scope)
