# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import connect_pb2 as connect__pb2


class authServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.req_pq = channel.unary_unary(
                '/meow.authService/req_pq',
                request_serializer=connect__pb2.Msg.SerializeToString,
                response_deserializer=connect__pb2.replyMsg.FromString,
                )
        self.req_DH_param = channel.unary_unary(
                '/meow.authService/req_DH_param',
                request_serializer=connect__pb2.NewMsg.SerializeToString,
                response_deserializer=connect__pb2.NewReplyMsg.FromString,
                )
        self.check_key = channel.unary_unary(
                '/meow.authService/check_key',
                request_serializer=connect__pb2.key.SerializeToString,
                response_deserializer=connect__pb2.val.FromString,
                )


class authServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def req_pq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def req_DH_param(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def check_key(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_authServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'req_pq': grpc.unary_unary_rpc_method_handler(
                    servicer.req_pq,
                    request_deserializer=connect__pb2.Msg.FromString,
                    response_serializer=connect__pb2.replyMsg.SerializeToString,
            ),
            'req_DH_param': grpc.unary_unary_rpc_method_handler(
                    servicer.req_DH_param,
                    request_deserializer=connect__pb2.NewMsg.FromString,
                    response_serializer=connect__pb2.NewReplyMsg.SerializeToString,
            ),
            'check_key': grpc.unary_unary_rpc_method_handler(
                    servicer.check_key,
                    request_deserializer=connect__pb2.key.FromString,
                    response_serializer=connect__pb2.val.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meow.authService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class authService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def req_pq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meow.authService/req_pq',
            connect__pb2.Msg.SerializeToString,
            connect__pb2.replyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def req_DH_param(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meow.authService/req_DH_param',
            connect__pb2.NewMsg.SerializeToString,
            connect__pb2.NewReplyMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def check_key(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meow.authService/check_key',
            connect__pb2.key.SerializeToString,
            connect__pb2.val.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
