// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: GRPC/connect.proto

package go_connection_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce     string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	MessageId int32  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GRPC_connect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_connect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_GRPC_connect_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Msg) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type ReplyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce       string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce string `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	MessageId   int32  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	P           int32  `protobuf:"varint,4,opt,name=p,proto3" json:"p,omitempty"`
	G           int32  `protobuf:"varint,5,opt,name=g,proto3" json:"g,omitempty"`
}

func (x *ReplyMsg) Reset() {
	*x = ReplyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GRPC_connect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMsg) ProtoMessage() {}

func (x *ReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_connect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMsg.ProtoReflect.Descriptor instead.
func (*ReplyMsg) Descriptor() ([]byte, []int) {
	return file_GRPC_connect_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyMsg) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ReplyMsg) GetServerNonce() string {
	if x != nil {
		return x.ServerNonce
	}
	return ""
}

func (x *ReplyMsg) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ReplyMsg) GetP() int32 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *ReplyMsg) GetG() int32 {
	if x != nil {
		return x.G
	}
	return 0
}

type NewMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce       string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce string `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	MessageId   int32  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ANumber     int32  `protobuf:"varint,4,opt,name=aNumber,proto3" json:"aNumber,omitempty"`
}

func (x *NewMsg) Reset() {
	*x = NewMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GRPC_connect_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMsg) ProtoMessage() {}

func (x *NewMsg) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_connect_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMsg.ProtoReflect.Descriptor instead.
func (*NewMsg) Descriptor() ([]byte, []int) {
	return file_GRPC_connect_proto_rawDescGZIP(), []int{2}
}

func (x *NewMsg) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *NewMsg) GetServerNonce() string {
	if x != nil {
		return x.ServerNonce
	}
	return ""
}

func (x *NewMsg) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *NewMsg) GetANumber() int32 {
	if x != nil {
		return x.ANumber
	}
	return 0
}

type NewReplyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce       string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce string `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	MessageId   int32  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	BNumber     int32  `protobuf:"varint,4,opt,name=bNumber,proto3" json:"bNumber,omitempty"`
}

func (x *NewReplyMsg) Reset() {
	*x = NewReplyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GRPC_connect_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewReplyMsg) ProtoMessage() {}

func (x *NewReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_connect_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewReplyMsg.ProtoReflect.Descriptor instead.
func (*NewReplyMsg) Descriptor() ([]byte, []int) {
	return file_GRPC_connect_proto_rawDescGZIP(), []int{3}
}

func (x *NewReplyMsg) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *NewReplyMsg) GetServerNonce() string {
	if x != nil {
		return x.ServerNonce
	}
	return ""
}

func (x *NewReplyMsg) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *NewReplyMsg) GetBNumber() int32 {
	if x != nil {
		return x.BNumber
	}
	return 0
}

type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthKey int32 `protobuf:"varint,1,opt,name=authKey,proto3" json:"authKey,omitempty"`
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GRPC_connect_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_connect_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_GRPC_connect_proto_rawDescGZIP(), []int{4}
}

func (x *Key) GetAuthKey() int32 {
	if x != nil {
		return x.AuthKey
	}
	return 0
}

type Val struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsTrue int32 `protobuf:"varint,1,opt,name=isTrue,proto3" json:"isTrue,omitempty"`
}

func (x *Val) Reset() {
	*x = Val{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GRPC_connect_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Val) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Val) ProtoMessage() {}

func (x *Val) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_connect_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Val.ProtoReflect.Descriptor instead.
func (*Val) Descriptor() ([]byte, []int) {
	return file_GRPC_connect_proto_rawDescGZIP(), []int{5}
}

func (x *Val) GetIsTrue() int32 {
	if x != nil {
		return x.IsTrue
	}
	return 0
}

var File_GRPC_connect_proto protoreflect.FileDescriptor

var file_GRPC_connect_proto_rawDesc = []byte{
	0x0a, 0x12, 0x47, 0x52, 0x50, 0x43, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x47, 0x52, 0x50, 0x43, 0x22, 0x3a, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x7e, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x4d,
	0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x67, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x67, 0x22, 0x7a, 0x0a, 0x06, 0x4e, 0x65, 0x77, 0x4d, 0x73, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x7f, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x1f, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x75,
	0x74, 0x68, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x75, 0x74,
	0x68, 0x4b, 0x65, 0x79, 0x22, 0x1d, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x73, 0x54, 0x72, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x73, 0x54,
	0x72, 0x75, 0x65, 0x32, 0x8c, 0x01, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x70, 0x71, 0x12, 0x09, 0x2e,
	0x47, 0x52, 0x50, 0x43, 0x2e, 0x4d, 0x73, 0x67, 0x1a, 0x0e, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x2e,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x0c, 0x72, 0x65,
	0x71, 0x5f, 0x44, 0x48, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x0c, 0x2e, 0x47, 0x52, 0x50,
	0x43, 0x2e, 0x4e, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x1a, 0x11, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x2e,
	0x4e, 0x65, 0x77, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x23, 0x0a,
	0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6b, 0x65, 0x79, 0x12, 0x09, 0x2e, 0x47, 0x52, 0x50,
	0x43, 0x2e, 0x6b, 0x65, 0x79, 0x1a, 0x09, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x76, 0x61, 0x6c,
	0x22, 0x00, 0x42, 0x33, 0x5a, 0x31, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d,
	0x67, 0x72, 0x70, 0x63, 0x3b, 0x67, 0x6f, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GRPC_connect_proto_rawDescOnce sync.Once
	file_GRPC_connect_proto_rawDescData = file_GRPC_connect_proto_rawDesc
)

func file_GRPC_connect_proto_rawDescGZIP() []byte {
	file_GRPC_connect_proto_rawDescOnce.Do(func() {
		file_GRPC_connect_proto_rawDescData = protoimpl.X.CompressGZIP(file_GRPC_connect_proto_rawDescData)
	})
	return file_GRPC_connect_proto_rawDescData
}

var file_GRPC_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_GRPC_connect_proto_goTypes = []interface{}{
	(*Msg)(nil),         // 0: GRPC.Msg
	(*ReplyMsg)(nil),    // 1: GRPC.replyMsg
	(*NewMsg)(nil),      // 2: GRPC.NewMsg
	(*NewReplyMsg)(nil), // 3: GRPC.NewReplyMsg
	(*Key)(nil),         // 4: GRPC.key
	(*Val)(nil),         // 5: GRPC.val
}
var file_GRPC_connect_proto_depIdxs = []int32{
	0, // 0: GRPC.authService.req_pq:input_type -> GRPC.Msg
	2, // 1: GRPC.authService.req_DH_param:input_type -> GRPC.NewMsg
	4, // 2: GRPC.authService.check_key:input_type -> GRPC.key
	1, // 3: GRPC.authService.req_pq:output_type -> GRPC.replyMsg
	3, // 4: GRPC.authService.req_DH_param:output_type -> GRPC.NewReplyMsg
	5, // 5: GRPC.authService.check_key:output_type -> GRPC.val
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GRPC_connect_proto_init() }
func file_GRPC_connect_proto_init() {
	if File_GRPC_connect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GRPC_connect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GRPC_connect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GRPC_connect_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GRPC_connect_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewReplyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GRPC_connect_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GRPC_connect_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Val); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GRPC_connect_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GRPC_connect_proto_goTypes,
		DependencyIndexes: file_GRPC_connect_proto_depIdxs,
		MessageInfos:      file_GRPC_connect_proto_msgTypes,
	}.Build()
	File_GRPC_connect_proto = out.File
	file_GRPC_connect_proto_rawDesc = nil
	file_GRPC_connect_proto_goTypes = nil
	file_GRPC_connect_proto_depIdxs = nil
}
