# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: biz.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='biz.proto',
  package='biz.v1',
  syntax='proto3',
  serialized_options=b'Z\006gen/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tbiz.proto\x12\x06\x62iz.v1\"D\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08\x61uth_key\x18\x02 \x01(\x05\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\"T\n\x1bUserRequest_with_sql_inject\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08\x61uth_key\x18\x02 \x01(\x05\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\"?\n\x0cUserResponse\x12\x1b\n\x05users\x18\x01 \x03(\x0b\x32\x0c.biz.v1.User\x12\x12\n\nmessage_id\x18\x02 \x01(\x05\"]\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x66\x61mily\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x0b\n\x03sex\x18\x05 \x01(\t\x12\x11\n\tcreatedAt\x18\x06 \x01(\t\"\x16\n\x03key\x12\x0f\n\x07\x61uthKey\x18\x01 \x01(\x05\"\x15\n\x03val\x12\x0e\n\x06isTrue\x18\x01 \x01(\x05\x32\xc4\x01\n\tget_users\x12\x36\n\tget_users\x12\x13.biz.v1.UserRequest\x1a\x14.biz.v1.UserResponse\x12V\n\x19get_users_with_sql_inject\x12#.biz.v1.UserRequest_with_sql_inject\x1a\x14.biz.v1.UserResponse\x12\'\n\tcheck_key\x12\x0b.biz.v1.key\x1a\x0b.biz.v1.val\"\x00\x42\x08Z\x06gen/v1b\x06proto3'
)




_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='biz.v1.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='biz.v1.UserRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auth_key', full_name='biz.v1.UserRequest.auth_key', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='biz.v1.UserRequest.message_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=89,
)


_USERREQUEST_WITH_SQL_INJECT = _descriptor.Descriptor(
  name='UserRequest_with_sql_inject',
  full_name='biz.v1.UserRequest_with_sql_inject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='biz.v1.UserRequest_with_sql_inject.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auth_key', full_name='biz.v1.UserRequest_with_sql_inject.auth_key', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='biz.v1.UserRequest_with_sql_inject.message_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=175,
)


_USERRESPONSE = _descriptor.Descriptor(
  name='UserResponse',
  full_name='biz.v1.UserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='users', full_name='biz.v1.UserResponse.users', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='biz.v1.UserResponse.message_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=240,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='biz.v1.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='biz.v1.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='family', full_name='biz.v1.User.family', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='biz.v1.User.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='biz.v1.User.age', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sex', full_name='biz.v1.User.sex', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='createdAt', full_name='biz.v1.User.createdAt', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=335,
)


_KEY = _descriptor.Descriptor(
  name='key',
  full_name='biz.v1.key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='authKey', full_name='biz.v1.key.authKey', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=359,
)


_VAL = _descriptor.Descriptor(
  name='val',
  full_name='biz.v1.val',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isTrue', full_name='biz.v1.val.isTrue', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=382,
)

_USERRESPONSE.fields_by_name['users'].message_type = _USER
DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['UserRequest_with_sql_inject'] = _USERREQUEST_WITH_SQL_INJECT
DESCRIPTOR.message_types_by_name['UserResponse'] = _USERRESPONSE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['key'] = _KEY
DESCRIPTOR.message_types_by_name['val'] = _VAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'biz_pb2'
  # @@protoc_insertion_point(class_scope:biz.v1.UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

UserRequest_with_sql_inject = _reflection.GeneratedProtocolMessageType('UserRequest_with_sql_inject', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST_WITH_SQL_INJECT,
  '__module__' : 'biz_pb2'
  # @@protoc_insertion_point(class_scope:biz.v1.UserRequest_with_sql_inject)
  })
_sym_db.RegisterMessage(UserRequest_with_sql_inject)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERRESPONSE,
  '__module__' : 'biz_pb2'
  # @@protoc_insertion_point(class_scope:biz.v1.UserResponse)
  })
_sym_db.RegisterMessage(UserResponse)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'biz_pb2'
  # @@protoc_insertion_point(class_scope:biz.v1.User)
  })
_sym_db.RegisterMessage(User)

key = _reflection.GeneratedProtocolMessageType('key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'biz_pb2'
  # @@protoc_insertion_point(class_scope:biz.v1.key)
  })
_sym_db.RegisterMessage(key)

val = _reflection.GeneratedProtocolMessageType('val', (_message.Message,), {
  'DESCRIPTOR' : _VAL,
  '__module__' : 'biz_pb2'
  # @@protoc_insertion_point(class_scope:biz.v1.val)
  })
_sym_db.RegisterMessage(val)


DESCRIPTOR._options = None

_GET_USERS = _descriptor.ServiceDescriptor(
  name='get_users',
  full_name='biz.v1.get_users',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=385,
  serialized_end=581,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_users',
    full_name='biz.v1.get_users.get_users',
    index=0,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_USERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_users_with_sql_inject',
    full_name='biz.v1.get_users.get_users_with_sql_inject',
    index=1,
    containing_service=None,
    input_type=_USERREQUEST_WITH_SQL_INJECT,
    output_type=_USERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='check_key',
    full_name='biz.v1.get_users.check_key',
    index=2,
    containing_service=None,
    input_type=_KEY,
    output_type=_VAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GET_USERS)

DESCRIPTOR.services_by_name['get_users'] = _GET_USERS

# @@protoc_insertion_point(module_scope)
